name: Auto Merge

on:
  pull_request:
    types: [labeled]
  check_suite:
    types: [completed]
  status: {}
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'auto-merge') }}
    steps:
      - name: Automerge PR
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "auto-merge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "rebase"
