name: Run CityBike Snapshot Hourly

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run script
        run: python get_citybike_snapshots.py

      - name: Dummy status check
        run: echo "This is a dummy status check for branch protection"

      - name: Get timestamp
        id: timestamp
        run: echo "commit_msg=Add snapshot at $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: ${{ steps.timestamp.outputs.commit_msg }}
          title: "Auto snapshot update"
          body: "This pull request was automatically generated by the workflow."
          branch: "auto/snapshot-update"
          delete-branch: true
          committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          labels: automerge

      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
